### ISSUE TITLE
Ampersand in String Breaks Deserialization

### ISSUE THREAD

**Issue by jottabyte** [RReverser/serde-xml-rs#106]
The following xml snippet parses perfectly:

\<game venue="Generic" game_pk="239523" venue_id="401" venue_w_chan_loc="USNY0996" home_team_link="/clubs/index.jsp?cid=t2412" box_link="/milb/stats/stats.jsp?gid=2008_06_10_dinrok_dacrok_1" />

However, if we add an "&" into the url to something like this:
\<game venue="Generic" game_pk="239523" venue_id="401" venue_w_chan_loc="USNY0996" home_team_link="/clubs/index.jsp?cid=t2412" box_link="/milb/stats/stats.jsp?gid=2008_06_10_dinrok_dacrok_1&t=g_box&did=milb" /> 

We get a Syntax error: Unexpected token inside an entity: =
I think the & is causing some kind of issue. I can work around it by adding .replace('&', ""), but this is obviously less than ideal.

Here's the actual xml that I'm parsing:
http://gd2.mlb.com/components/game/rok/year_2008/month_06/day_10/gid_2008_06_10_dinrok_dacrok_1/linescore.xml

**Comment by punkstarman** [comment]
This error comes directly from xml-rs when parsing the document. This is correct behavior given the following excerpt from the XML specification.

> The ampersand character (&) and the left angle bracket (<) must not appear in their literal form, except when used as markup delimiters, or within a comment, a processing instruction, or a CDATA section. If they are needed elsewhere, they must be escaped using either numeric character references or the strings " &amp; " and " &lt; " respectively.
(see https://www.w3.org/TR/xml/#syntax)

From what I understand, the document is ill-formed. You will have to petition MLB to conform to the norm. Or as a workaround, you should replace `&` with `&amp;`.

**Comment by jottabyte** [comment]
That makes a lot of sense. Your workaround works perfectly. Thanks for the quick response!

**Comment by punkstarman** [comment]
I'm glad to help 😉
