### ISSUE TITLE
Serde via quick-xml

### ISSUE THREAD

**Issue by andreivasiliu** [RReverser/serde-xml-rs#108]
Re: https://github.com/RReverser/serde-xml-rs/issues/61 - does that decision still hold?

A while ago I managed to hack my way through serde-xml-rs, and made it work with quick-xml, which sped it up tremendously; it wasn't pretty, and it didn't have a serializer, so I didn't open a PR. But now that I want a fast serde parser again, I'd be willing to clean and finish it up.

The way I did it was to make a trait that mimics xml-rs's API, base the whole deserialzier around that trait by making it generic, and then implement the trait for both xml-rs and quick-xml.

I could raise a PR in which I add this (gated by a disabled-by-default feature flag) for serde-xml-rs.

Or I could fork it into serde-quick-xml, drop support for xml-rs, and maintain it myself.

Edit: Or I could just completely swap out xml-rs for quick-xml in this crate.

Which would you prefer?

**Comment by punkstarman** [comment]
I believe that the decision still stands.

Maybe @RReverser, you would like to weigh in on this?
