### ISSUE TITLE
How to deserialize differents elements in one vector

### ISSUE THREAD

**Issue by Dawen18** [RReverser/serde-xml-rs#110]
Hi, I have this XML

```xml
<content id="content1">
    <text id="txt1" style="style1">
	<value>
	    <![CDATA[Lorem ipsum dolor sit amet.]]>
        </value>
    </text>
    <image id="img1" src="/foo/bar"/>
    <text>...</text>
</content>
```

`<content>` is a child of an other tag but for more readability not appears above.

I need to deserialize `text`, `image` and some other tags in one same vector and keep order like in xml file. I don't understand how to do this.

I've tried with enum but I can't put them in the same vector.

Thanks for your help.

**Comment by punkstarman** [comment]
I think this is very similar to #109. As well as using an enum, you need to rename a field on the type that represents `content` to `$value`.

**Comment by Dawen18** [comment]
Of course it works with `$value`

Sorry I've missed this in documentation.

Thanks a lot.

**Comment by punkstarman** [comment]
No problem. I'm happy to help :smile:
