### ISSUE TITLE
Issue with special character

### ISSUE THREAD

**Issue by hybrisCole** [RReverser/serde-xml-rs#115]
Hello,

So I have this xml node:
<Nombre>José</Nombre>

but I'm receiving it on the rust side as "JosÃ©".

Is there a workaround/solution to work with these special chars?

Thx

**Comment by punkstarman** [comment]
@hybrisCole , thank you for submitting this issue.

Can you please provide more details. The relevant parts of your source code and a copy or extract of the file would be useful.

If you have time, a minimal example reproducing the bug would be even better.

**Comment by cole-acepph** [comment]
Hi, 

Sorry about it, just found out that my issue is when I'm parsing email contents.

Not related to serde-xml-rs.

Regards,

**Comment by hybrisCole** [comment]
Hi,

Sorry about it, just found out that my issue is when I'm parsing email contents.

Not related to serde-xml-rs.

Regards,
