### ISSUE TITLE
Release with thiserror?

### ISSUE THREAD

**Issue by m-doughty** [RReverser/serde-xml-rs#123]
The library was updated to use `thiserror` a couple of months ago, but there's no crate release with this functionality (and `Sync` error support).

Please could we get a release with this support turned on?

**Comment by RReverser** [comment]
@punkstarman Do you want to take care of this or are there other breaking changes in the pipeline to combine into a new release first?

**Comment by punkstarman** [comment]
@RReverser, I can push a release tomorrow.

**Comment by punkstarman** [comment]
Done :heavy_check_mark:
