### ISSUE TITLE
/> inside string content causes Syntax("Unexpected token: />") error

### ISSUE THREAD

**Issue by Mingun** [RReverser/serde-xml-rs#134]
Parsing such perfectly well-formed XML document lead to error:
```rust
#[test]
fn valid_xml() {
  let _: String = serde_xml_rs::from_str("<tag>/></tag>").unwrap();
}
```
XML documents with such symbols can be, for example, produced by mature XmlBeans Java library, when you serialize XML document, embedded in another XML document as string.

**Comment by punkstarman** [comment]
You'll have to take this issue upstream to https://github.com/netvl/xml-rs.
