### ISSUE TITLE
Clarify how attributes are handled

### ISSUE THREAD

**Issue by Timmmm** [RReverser/serde-xml-rs#140]
In the Github readme you have this example:

```
struct Item {
    pub name: String,
    pub source: String
}
// <Item name="hello" source="world.rs" />
```

And in the documentation you have:

```
struct Item {
    name: String,
    source: String,
}
// <Item><name>Banana</name><source>Store</source></Item>
```

It's not immediately obvious how the different styles are handled. E.g. what happens if you have this:

    <Item name="Orange"><name>Banana</name>...

If I do 

```
struct Item {
    name: String,
    source: Vec<String>,
}
```

Will it still decode this:

    <Item source="Orange">...

Or only this:

    <Item><source>Store</source><source>Jungle</source>...

It would be good to document it.

**Comment by punkstarman** [comment]
@Timmmm, good remark.

When I have time to put toward it, I am planning on fleshing out the documentation with some more detailed cases. Not in the README, but in code documentation so that it will show up on docs.rs.

At the moment, the documentation refers the developer to the tests, which aren't always easy to navigate.

**Comment by reza-ebrahimi** [comment]
Any progress here?

**Comment by elpiel** [comment]
Is it possible to force an element or an attribute?
It seems that regular Struct fields deserialization handles both attributes and elements and does not distinguish between them.

**Comment by punkstarman** [comment]
Soon I will be introducing a breaking change so that elements and attributes are handled differently.

**Comment by elpiel** [comment]
> Soon I will be introducing a breaking change so that elements and attributes are handled differently.

Great! How can I help?
I've been fighting with this all day.... 😅

**Comment by elpiel** [comment]
> @elpiel, I don't know. I appreciate the moral support.
> 
> You can also have a look at my prototype implementation: https://github.com/punkstarman/serde-xml
 Quck Q: why have you chosen to use rename instead an attribute like `serde_with`?

The API seems a bit confusing to me with `rename=$value` especially since I'm using the crate in a project for a first time.

**Comment by elpiel** [comment]
Hey @punkstarman ,
I wanted to check up on you if you had any time to work on the deserializer for attributes?

PS: Congratulations on finishing up the serializer! :tada:

**Comment by punkstarman** [comment]
@elpiel, I haven't gotten to it, but would like to soon. I think the 2 top priorities are that and namespace support.
