### ISSUE TITLE
Example with EventReader?

### ISSUE THREAD

**Issue by lumost** [RReverser/serde-xml-rs#141]
Would it be possible to incude an example with an event reader? It's unclear how to deserialize from an event stream between the docs here and xml-rs.

**Comment by punkstarman** [comment]
It would. Thank you @lumost for the suggestion.

As a stopgap, basically the point of instantiating the `EventReader` yourself is to be able to choose the configuration options. By default, this crate activates `trim_whitespace`, `whitespace_to_characters`, `cdata_to_characters`, `ignore_comments` and `coalesce_characters`.

Once you have an `EventReader` you can deserialize using the following code.

```rust
use serde_xml_rs::de::Deserializer;

let result = T::deserialize(&mut Deserialize::new(event_reader));
```
where `T` is the type being deserialized to.
