### ISSUE TITLE
Any chance for a release?

### ISSUE THREAD

**Issue by bminixhofer** [RReverser/serde-xml-rs#145]
Hi! I currently depend on serde-xml-rs in a project I would like to release on crates.io: https://github.com/bminixhofer/nlprule.

I need the fix for untrimmed whitespace (https://github.com/RReverser/serde-xml-rs/pull/79) so I currently have to depend on the git repo.

Is there any chance you could do a patch release to include this fix? The last release was ~ 10 months ago and it looks like there were some other useful fixes in the meantime too. Thanks.

**Comment by punkstarman** [comment]
OK @bminixhofer, I'll try to find time this week.

**Comment by bminixhofer** [comment]
Thanks a lot! I really appreciate it.

**Comment by punkstarman** [comment]
:heavy_check_mark: done
