### ISSUE TITLE
Add a default catchall case to enum to allow parsing elements with an unknown name

### ISSUE THREAD

**Issue by lovasoa** [RReverser/serde-xml-rs#146]
Let's say I have an xml document with the following form : 

```xml
<root>
  <item1 />
  <item2 />
   ...
  <item999 />
</root>
```

and I am only interested in elements of type `item1` and `item2`.

Currently, there is no good way to parse such a document with serde-xml-rs.

## Try 1

I can write the following 

```rust
struct Root {
   item1: Vec<Item1>,
   item2: Vec<Item2>,
}
```

Unfortunately, it won't work with documents such as 

```xml
<root>
  <item1 />
  <item2 />
  <item1 />
</root>
```

because of https://github.com/RReverser/serde-xml-rs/issues/55 which has been a open issue since 2017

## Try 2

I can write 

```rust
struct Root {
    #[serde(rename = "$value")]
    items: Vec<Item>,
}


#[serde(rename_all = "lowercase")]
enum Item {
    Item1(Item1Props),
    Item2(Item2Props),
    Item3,
    ...
    Item999
}
```

but this requires me to know ahead of time all the possible tags that can occur in addition  of `<item1>` and `<item2>`, which I don't.

## Possible solution

I would like to add a way to parse all unknown tags in a single variant, like this

```rust
#[serde(rename_all = "lowercase")]
enum Item {
    Item1(Item1Props),
    Item2(Item2Props),
    #serde(rename = "$other")
    Other
}
```

This follows the same principle as the existing `$value`, but allows parsing any incoming tag without error.

For instance 

```xml
<root> <item1 /> <item999 /> <item1 /> </root>
```

would be parsed as 

```rust
Root { items : vec![ Item1{}, Other, Item1{} ] }
```

Is this issue clear enough ? Would you be interested in a PR implementing that ?

**Comment by lovasoa** [comment]
Reading more documentation, I see that serde has a [`#[serde(other)]`](https://serde.rs/variant-attrs.html#other) enum attribute, but it works only on unit enum variants, and this crate [refuses](https://github.com/RReverser/serde-xml-rs/blob/master/src/de/var.rs#L59-L62) to deserialize xml tags with attributes or children to unit variants.

**Comment by lovasoa** [comment]
The best I found at the moment is 


```rust
#[derive(Deserialize, Debug)]
#[serde(rename_all = "lowercase")]
enum ItemOrOther {
    Item1,
    Item2,
    #[serde(other, deserialize_with = "deserialize_ignore_any")]
    Other,
}

fn deserialize_ignore_any<'de, D: Deserializer<'de>>(deserializer: D) -> Result<(), D::Error> {
    serde::de::IgnoredAny::deserialize(deserializer)?;
    Ok(())
}
```

**Comment by punkstarman** [comment]
Thank you @lovasoa for your detailed info.

I am closing this because :
- I deem that your latest comment is not just a workaround but the proper solution;
- the issue seems to be duplicating #55.
