### ISSUE TITLE
moving this repository to a new home for better maintenance

### ISSUE THREAD

**Issue by efx** [RReverser/serde-xml-rs#155]
Hello folks,

First off, a huge thank you to @RReverser for starting this project.
I have benefited from learning from an open serde project for XML.

How do you both feel about creating an xml-rs group on GitHub and moving this project there?
I noticed [pdf-rs](https://github.com/pdf-rs) does this. 
I feel like it is a worthwhile idiom to manage open projects on GitHub.

I am in the business for a high-quality XML serializer and would love to contribute my efforts to something open. 
I see maintenance as the blocker for this specific repository now.

/cc @punkstarman @RReverser 

See backstory in https://github.com/RReverser/serde-xml-rs/issues/65#issuecomment-384269765

**Comment by efx** [comment]
As I better understand serde, serializers and working XML in Rust, I am withdrawing this request.

Serde's designer notes that arbitrary XML serializing does not fit serde's design well:
- https://github.com/serde-rs/serde-rs.github.io/pull/112#pullrequestreview-408688152
- https://github.com/serde-rs/serde/issues/1725#issuecomment-626243415

He recommends the community establish libraries specialized to the needed XML formats.
[strong-xml](https://github.com/PoiScript/strong-xml) is a good example of how custom derives for can flexibly solve the Rust to XML serialization problem.

In my case I need a writer for [ECMA-376](https://www.ecma-international.org/publications-and-standards/standards/ecma-376/)'s WordprocessingML, the specification behind Microsoft Word.

serde-xml-rs gets me close but not quite. I thus plan on using strong-xml combined with other procedural macros to better align Rust data structures writing to conformant WordprocessingML.

**Comment by RReverser** [comment]
I think moving this repo to `serde` umbrella would be still useful and it's something we discussed in the past, but for your specific requests, yeah, the best choice is to create separate libraries if `serde-xml-rs` doesn't cover your needs.

**Comment by RReverser** [comment]
@oli-obk @dtolnay I think we talked about this in the past and you were open to this - if still the case, could you please give me permissions to create repos under serde-rs so that I could transfer it there?

**Comment by dtolnay** [comment]
Moving to the serde org is effectively an endorsement that "you should use this" which, as linked above, is not my position. Moving to the serde-deprecated org (https://github.com/serde-deprecated) and archiving the repo is a possibility, but that doesn't seem necessary if the library is still loosely maintained over here -- and the set of maintainers is disjoint from serde anyway.

**Comment by RReverser** [comment]
> Moving to the serde-deprecated org (@serde-deprecated) and archiving the repo is a possibility

Uh, that sounds weird / wrong. It's certainly not deprecated - maybe you're confusing with serde-xml (the old implementation)?

**Comment by RReverser** [comment]
> Uh, that sounds weird / wrong. It's certainly not deprecated - maybe you're confusing with serde-xml (the old implementation)?

I checked the linked comment, apparently not. It's still weird to mark it as deprecated or not recommended just because it doesn't cover _all_ XML schemes.
