### ISSUE TITLE
Question: How to deserialize arbitrary tag?

### ISSUE THREAD

**Issue by thorstenhater** [RReverser/serde-xml-rs#161]
I have a question and I hope this is right channel to ask. I am trying to deserialize a data format based
on XML using serde, which essentially boils down to
```xml
<root>
  <kind name="A" />
  <item kind="A">
    ...
  </item>
  <kind name="B" />
  <B>
    ...
  </B>
</root>
```
Note how the `B` tag can be used a shorthand for `item kind="B"`.
I have a working implemention for the non-shorthand part that looks like this
```rs
// These have more inner structure, omitted for brevity
#[deriving(Deserialize)]
struct Kind { ... }
#[deriving(Deserialize)]
struct Item { ... }

#[deriving(Deserialize)]
enum RootBody {
   Item(Item),
   Kind(Kind),
}

#[deriving(Deserialize)]
struct Root {
  #[serde(rename="$value")]
  body: Vec<RootBody>,
}
```
However, how to capture the short-hand feature? Using the pattern from the
JSON examples 
```rs
#[deriving(Deserialize)]
struct Root {
  #[serde(rename="$value")]
  body: Vec<RootBody>,
  #[serde(flatten)]
  unknown: Map<String, Value>
}
```
fails with `Custom("missing field $value")'`. I have also tried `deserialize-enum-str` and 
had no success.

**Comment by punkstarman** [comment]
You have come to the right place.

Unfortunately, `flatten` overrides `$value`. I'm afraid that it's one or the other.

**Comment by punkstarman** [comment]
Also, using `unknown: Map<String, Value>` works with JSON or YAML where the same key can't occur twice. It doesn't work so well with XML.

**Comment by thorstenhater** [comment]
Thanks, do you have any pointers on how to implement this? Preferably without leaving serde behind, of course.
A custom `deserialize` seems currently the only way I can see, although I have never delved into that.

**Comment by punkstarman** [comment]
I'm afraid that I don't have any ideas on how to do that.

**Comment by thorstenhater** [comment]
Thanks for your answers, I settled on re-writing the data in memory. Not as elegant as I would like, but it works for the
time being.

That said, this functionality would still be useful, as there are XML schemata using `<xs:any>` which I will have to deal
with in the near future.
