### ISSUE TITLE
Document how attributes can be used

### ISSUE THREAD

**Issue by Corasonn** [RReverser/serde-xml-rs#168]
```
A {
    pub b: String
}

let foo = A {
    b: "bar".to_string()
}

```
```
let xml = to_string(foo).unwrap();
```

This produces:

`<A><b>bar</bar><A>`

It's what I expect, but what I need is:

` <A b="bar"><A>`
 
 How can I achieve this? I didn't find any documentation about it.

**Comment by punkstarman** [comment]
Thank you @Corasonn. Unfortunately what you want can't be achieved yet. I am working on rewriting the serializer completely based on a prototype of mine (https://github.com/punkstarman/serde-xml).

**Comment by punkstarman** [comment]
This is a duplicate of #140.
