### ISSUE TITLE
Does not handle surrogate pairs?

### ISSUE THREAD

**Issue by remexre** [RReverser/serde-xml-rs#21]
I get a syntax error when decoding the following element:

```
 <sms protocol="0" address="redacted" date="1487032373307" type="2" subject="null" body="&#55357;&#56495;" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { pos: 3304:101, kind: Syntax("Invalid decimal character number in an entity: #55357") }', /checkout/src/libcore/result.rs:859
```

**Comment by RReverser** [comment]
Hmm, not sure about this. We don't parse XML ourselves, just wrap [xml-rs](https://github.com/netvl/xml-rs) for that - could you please report an issue upstream and comment here when/if it's fixed so that I could bump dependency? Thanks for the report!
