### ISSUE TITLE
Structure for optionally-empty lists

### ISSUE THREAD

**Issue by indiv0** [RReverser/serde-xml-rs#23]
I have a use case which involves parsing optionally-empty lists, like so:

```xml
<mylist>
    <item name="foo"></item>
    <item name="bar"></item>
</mylist>
```

or:

```xml
<mylist>
</mylist>
```

What would be the equivalent rust struct to represent this with serde-xml-rs?

**Comment by RReverser** [comment]
This one is exactly covered in readme:

```
#[derive(Debug, Deserialize)]
struct Project {
    pub name: String,

    #[serde(rename = "Item", default)]
    pub items: Vec<Item>
}
```

Here `items` maps to optional list of `<Item ... />` tags.

**Comment by indiv0** [comment]
Oh. My bad, I was missing the `#[serde(default)]`. Thanks!
