### ISSUE TITLE
Infinite Loop when parsing Vec

### ISSUE THREAD

**Issue by Boscop** [RReverser/serde-xml-rs#3]
This results in an infinite loop:
```rust
let tickets: Vec<Ticket> = deserialize(xml.as_bytes()).unwrap();
```
When used on a xml doc that has multiple root elements.

**Comment by RReverser** [comment]
XML doc can't have multiple root elements, it's malformed XML in that case.

**Comment by Boscop** [comment]
Yes, but even in that case it should not cause an infinite loop!
XML can't be trusted to be valid.

**Comment by RReverser** [comment]
Fair enough. Want to give a try on the PR?
