### ISSUE TITLE
Deserialize with xml header

### ISSUE THREAD

**Issue by kjeremy** [RReverser/serde-xml-rs#47]
I'm trying to deserialize xml that starts with:

```xml
<?xml version=”1.0” standalone=”yes”?>
```

but it fails.  Is there a way to ignore the header?

**Comment by oli-obk** [comment]
Not yet, but this is trivial to implement in the parser. Maybe we should bail out with an error if standalone is "no"

**Comment by kjeremy** [comment]
I'm looking at this right now (I'm a total rust newbie) and I don't understand why it doesn't work.

The following in `inner_next` should handle it:
```rust
match r.map_err(ErrorKind::Syntax)? {
                XmlEvent::StartDocument { .. } |
```

**Comment by oli-obk** [comment]
That seems too general. You'd skip over every kind of syntax error. I also am not sure if `xml-rs` even supports recovering from syntax errors. Have you checked whether xml-rs supports headers in some way?

**Comment by RReverser** [comment]
xml-rs definitely supports `<?xml ...?>` if that's what you mean by headers, it's in its own test suite: https://github.com/netvl/xml-rs/blob/master/tests/documents/sample_1.xml

**Comment by RReverser** [comment]
And it's returned as `StartDocument`, which we already ignore. @kjeremy please provide more details - full reproducible example and error message you're getting.

**Comment by kjeremy** [comment]
Right it returns `StartDocument` which is why I'm surprised.  The following test illustrates the problem and fails with a parsing error.

```rust
#[test]
fn ignore_header() {
    init_logger();

    let s = r#"
        <?xml version=”1.0” standalone=”yes”?>
        <item name="hello" source="world.rs" />
    "#;

    let item: Item = from_str(s).unwrap();

    assert_eq!(
        item,
        Item {
            name: "hello".to_string(),
            source: "world.rs".to_string(),
        }
    );
}
```

**Comment by RReverser** [comment]
@kjeremy If it's literally your XML, then the problem appears to be these weird quotes you have in the test - `”` (U+201D) in `<?xml ...?>` vs normal quote `"` (U+0022) everywhere else. Perhaps copied incorrectly from somewhere?

**Comment by kjeremy** [comment]
Ah ha! Good catch.  Yes I had originally copied some XML from a word doc.  Replacing the quotes fixed the issue.  I will close this.
