### ISSUE TITLE
bump new version as RC

### ISSUE THREAD

**Issue by farodin91** [RReverser/serde-xml-rs#53]
@RReverser It would be cool to release to crates.io, the current state as a RC.

**Comment by dylanede** [comment]
I would also be interested in this happening.

**Comment by robo-hamburger** [comment]
It looks like #20 was fixed a while ago but doesn't seem to work on the crate published on crates.io.

**Comment by jimrybarski** [comment]
Is anything in particular blocking this that I could help out with?

**Comment by lancecarlson** [comment]
@RReverser Can we get a new release? Just realized bools work in the git version and I've frozen to that version for the time being.

**Comment by jimrybarski** [comment]
I was able to use [serde-xml-any](https://crates.io/crates/serde-xml-any) as a drop-in replacement for this repo, and since it's published on crates.io with #20 fixed, I could publish my crate finally. I don't know how universal this solution will be but I hope it helps.

**Comment by Dushistov** [comment]
@jimrybarski 

Hmm, @RReverser gives access to this repo to @punkstarman, see #65.
May you can cooperate with @punkstarman ?

**Comment by punkstarman** [comment]
I have access to this repo, but I am not an owner of the crate on crates.io
The owners currently are @RReverser and @oli-obk.

**Comment by RReverser** [comment]
@punkstarman I've sent you an invite on crates.io too now.

**Comment by punkstarman** [comment]
Thanks :+1:

**Comment by punkstarman** [comment]
Version 0.3.0 has been released on crates.io

see #65
