### ISSUE TITLE
How to serialize struct field as xml attribute?

### ISSUE THREAD

**Issue by Boscop** [RReverser/serde-xml-rs#57]
How to serialize a struct field as xml attribute?

What I want to get is:
`"<Message><ARTSCommonHeader MessageType="Request"/><SystemTransaction ActionCode="Update"><DeviceTime>2017-10-11T12:53:00</DeviceTime></SystemTransaction></Message>"`

But if I use normal struct fields for MessageType and ActionCode, they are not serialized as attributes but as tags (`<MessageType>Request</MessageType>` and `<ActionCode>Update</ActionCode>`).

Is there a `#[annotation]` I should use for the struct fields?

**Comment by oli-obk** [comment]
This is not yet implemented. It is covered in #49
