### ISSUE TITLE
Option not working with rename macro

### ISSUE THREAD

**Issue by marshauf** [RReverser/serde-xml-rs#6]
The following code fails with:
``
thread 'it_works' panicked at 'called `Result::unwrap()` on an `Err` value: Expected token XmlEvent::StartElement { name, attributes, .. }, found En
dElement(Item)', /checkout/src/libcore/result.rs:859
``

```rust
#[macro_use] extern crate serde_derive;
extern crate serde_xml_rs;

use serde_xml_rs::deserialize;

#[derive(PartialEq, Debug, Serialize, Deserialize)]
struct Item {
    pub name: String,
    pub source: String,
}

#[derive(PartialEq, Debug, Serialize, Deserialize)]
struct Project {
    pub name: String,

    #[serde(rename = "Item")]
    pub items: Option<Item>,
}

#[test]
fn it_works() {
    let s = r##"
        <Project name="my_project">
            <Item name="hello" source="world.rs"/>
        </Project>
    "##;
    let project: Project = deserialize(s.as_bytes()).unwrap();
    println!("{:#?}", project);
}
```

If I remove ``#[serde(rename = "Item")]`` and rename Project.items to Project.item the test runs without a failure.

**Comment by RReverser** [comment]
> to Project.item

Are you saying that even a lowercase variant works?

**Comment by farodin91** [comment]
This code works on the latest master.

**Comment by oli-obk** [comment]
🎉
