### ISSUE TITLE
Publish new crates version

### ISSUE THREAD

**Issue by TylerWasniowski** [RReverser/serde-xml-rs#65]
Can you please publish change to crates.io? Thank you!

**Comment by futile** [comment]
I think this would need to be a breaking change, as the README still talks about `deserialize`, but it's actually called `from_str` now I think.

**Comment by frol** [comment]
@RReverser Is there any chance to release the existing changes any time in future?

**Comment by RReverser** [comment]
Yes, sorry. I can release existing ones, but in general I think I'll start looking for a new maintainer to take care of this library - it was fun to write it, but as I don't have a need to use it myself anymore, it's hard to find time for the maintenance it deserves and I'd better give the "keys" to someone who can and want to take care of it.

**Comment by punkstarman** [comment]
@RReverser, I am interested in taking over. I think that the lack of good XML ser/de for Rust is a gaping big hole. Even if JSON, YAML and others are taking over, XML will still be around for a while.

**Comment by RReverser** [comment]
@punkstarman Sorry for missing your response! Let me invite you to the repo.

**Comment by punkstarman** [comment]
Thanks.

**Comment by punkstarman** [comment]
@RReverser, over the next few weeks, can you share with me any guidelines/pointers as to how you have been running this project?

**Comment by RReverser** [comment]
@punkstarman Does "poorly" work as an asnwer? :) On a serious note, I'm happy to review and discuss ideas etc. but right now @dtolnay's reasoning in https://github.com/serde-rs/serde/issues/1446#issuecomment-448893465 sounds good to me.

Initially, when I received the first PR for serialiser, I was hoping for proper roundtrip support (and ideally I'd still expect it for any serialiser changes), but it's certainly not the priority compared to being parse most popular XML schemes.

**Comment by punkstarman** [comment]
OK, no problem. So I suggest that once we're into 2019 at which point I will have time again to contribute, I will just start hacking away.

I wouldn't mind being added as an owner of the crate on crates.io so I can publish new versions.

**Comment by RReverser** [comment]
SGTM, just please be careful with breaking changes / semver, and also let's not commit to 1.0 in foreseeable future until we have a clearly stable vision and APIs.

**Comment by punkstarman** [comment]
Done.

Version 0.3.0 has been tagged and published to crates.io.
