### ISSUE TITLE
Serialization Support

### ISSUE THREAD

**Issue by Michael-F-Bryan** [RReverser/serde-xml-rs#7]
From serde-rs/xml#35 it sounds like this might soon be the de facto crate for using xml with serde. Are there any plans for implementing [Serialization][ser]?

If so, is there anything I can do to help? I'm wanting to serialize to and from XML in one of my projects and it'd be nice to use `serde` instead of having to implement it myself with some sort of `ToXML` trait.

[ser]: https://docs.serde.rs/serde/trait.Serializer.html

**Comment by RReverser** [comment]
@Michael-F-Bryan Sure, implementing serializer is more than welcome.

Ideally, my plan was to also reduce deserialization only to cases where the roundtrip would be possible and correct, but this does not necessarily have to be in scope of initial serializer implementation.

**Comment by oli-obk** [comment]
There is now initial serialization support. I suggest we track specific serialization issues in a separate issue.

**Comment by oli-obk** [comment]
@RReverser can you also give me publishing rights on crates.io? Currently I can push to this repo but not to crates.io

**Comment by RReverser** [comment]
@oli-obk Ok, sure.

**Comment by RReverser** [comment]
Done.
