### ISSUE TITLE
Cannot serialize sequence of tags

### ISSUE THREAD

**Issue by ebkalderon** [RReverser/serde-xml-rs#76]
I was using `serde-xml-rs` with the [`vkxml`](https://github.com/terrybrashaw/vkxml) crate in one of my projects, and although the structures it exposes implement `Serialize`, the serialization fails due to `serialize_seq()` not being supported in `serde-xml-rs`, as described in [this code block](https://github.com/RReverser/serde-xml-rs/blob/551c78d155cac89815e28d0f36a87029a8bf2a62/src/ser/mod.rs#L236-L241).

In this library, a valid `vk_new.xml` file is represented an ordered sequence of `RegistryElement` tags (see the [lib.rs](https://github.com/terrybrashaw/vkxml/blob/master/src/lib.rs#L8)). Therefore, it intuitively appears straightforward to iterate over each element in the sequence and serialize them in turn. However, the comment left in the `serialize_seq()` method leads me to believe that this task isn't as simple as it seems.

Would anyone please elaborate on why this behavior isn't supported?

**EDIT:** I see that https://github.com/RReverser/serde-xml-rs/pull/36 has been open for about a year. What's the status?

**Comment by jrmiller82** [comment]
It's because it's a *de*serializer only as of now.

**Comment by flying-sheep** [comment]
It does have a serializer implementation, albeit limited. If I can help to get the ball rolling, I will!
