### ISSUE TITLE
Update to Serde 1.0

### ISSUE THREAD

**Issue by dtolnay** [RReverser/serde-xml-rs#9]
Release notes: https://github.com/serde-rs/serde/releases/tag/v1.0.0

**Comment by theduke** [comment]
This is done now, can be closed.

**Comment by RReverser** [comment]
Done under 0.2.0.

**Comment by craftytrickster** [comment]
You're probably going to want to change the Readme and crates.io information to reflect this.

**Comment by craftytrickster** [comment]
@dtolnay Since https://github.com/serde-rs/xml/issues/3 claims that it is deprecated in favor of this repo, should this be moved to the serde org instead of serde-rs/xml?

**Comment by RReverser** [comment]
@craftytrickster Technically 1.0 matches 0.9+, but yeah, could update it 😄

**Comment by theduke** [comment]
Can be closed?
